pipeline {
    agent any
    
    stages {
         stage('Install Docker and Kubectl') {
            steps {
                // Install Docker
                sh 'curl -fsSL https://get.docker.com -o get-docker.sh'
                sh 'sh get-docker.sh'
                sh 'docker version'
                
                // Install kubectl
                sh 'curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"'
                sh 'chmod +x kubectl'
                sh 'mv kubectl /usr/local/bin'
                sh 'kubectl version --client'
            }
        }

        stage('Clone Repository') {
            steps {
                // Clone the repository
                git url: 'https://github.com/mahmoud254/jenkins_nodejs_example.git', branch: 'k8s_task'
            }
        }
        
        stage('Build Image') {
            steps {
                 
                // Build the image as per your requirements
                sh 'docker build -t nodejs-app:latest .'
            }
        }
        
        stage('Push to Nexus') {
            steps {
                // Login to the Nexus registry
                withCredentials([usernamePassword(credentialsId: 'nexus', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    sh "docker login -u $USERNAME -p $PASSWORD 10.111.33.70:5000"
                }
                
                // Tag the image with Nexus registry information
                sh 'docker tag nodejs-app:latest 10.111.33.70:5000/repository/nexus-repo/nodejs-app:latest'
                
                // Push the image to Nexus registry
                sh 'docker push 10.111.33.70:5000/repository/nexus-repo/nodejs-app:latest'
            }
        }
    
      
    }
}
            
