apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: Jenkins-Role
rules:
- apiGroups: [""]
  resources: ["deployments"]
  verbs: ["get", "watch", "list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: Jenkins-RoleBinding
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: dev
roleRef:
  kind: ClusterRole
  name: Jenkins-Role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: Tools-Role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "get", "watch", "list"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: Tools-RoleBinding
subjects:
- kind: ServiceAccount
  name: default
  namespace: tools
roleRef:
  kind: ClusterRole
  name: Tools-Role
  apiGroup: rbac.authorization.k8s.io
