pipeline {
    agent any
    
    stages {
         stage('Install Kubectl') {
            steps {
                // Install kubectl
                sh 'curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"'
                sh 'chmod +x kubectl'
                sh 'mv kubectl /usr/local/bin'
                sh 'kubectl version --client'
            }
             
          stage('Deploy Image on minikube') {
            steps {
                // clone repo
                git credentialsId:'GitHub' ,url:'https://github.com/Mohamed-Sharif/ITI-Final-Project.git', branch:'main' 
                
                // Deploy the app from the Nexus registry to minikube
                sh """
                cd App_Manifests
                kubectl apply -f app_secrets.yaml 
                kubectl apply -f nodejs_app.yaml 
                """
            }
        }
    }
}
