---
- name: Install and configure Minikube
  hosts: localhost
  become: yes
  become_method: sudo
  
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common']

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Install Minikube dependencies
      apt:
        name: ['conntrack', 'ebtables', 'socat']

    - name: Download Minikube
      get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        dest: /usr/local/bin/minikube
        mode: 0755

    - name: Start Minikube cluster
      command: minikube start --driver=docker --force

    - name: Set KUBECONFIG environment variable
      lineinfile:
        dest: $HOME/.bashrc
        line: 'export KUBECONFIG=$HOME/.kube/config'
        create: yes
      vars:
        home_dir: "{{ ansible_env.HOME }}"
